### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by fabiosirna** [arsenetar/dupeguru#849] opened 2021-02-20 16:19 UTC
**Describe the bug**
IDK

**To Reproduce**
1. open dupeguru
2. add 2 folders
3. See error

**Expected behavior**
Finding duplicated files

**Desktop (please complete the following information):**
 - OS: OSX
 - Version  11.2.1

**Additional context**
the folder that I'm trying to find duplicated files is mounted with rclone

**Error Report**

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.16 (Build 20D74)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:1612'

**Comment by arsenetar** [comment] 2021-08-22 00:35
Duplicate of #439

**Closed as completed by arsenetar** 2021-08-22 00:35 UTC
Labels: bug
