### ISSUE TITLE
Error when closing without saving (opted out)

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [arsenetar/dupeguru#379] opened 2016-07-19 23:40 UTC
Installed from the ppa here; on 14.04
https://launchpad.net/~hsoft/+archive/ubuntu/ppa/

```
Application Name: dupeGuru
Version: 4.0.0

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/result_window.py", line 321, in appWillSavePrefs
    prefs = self.app.prefs
AttributeError: 'NoneType' object has no attribute 'app'
```

```
Application Name: dupeGuru
Version: 4.0.0

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/details_dialog.py", line 40, in appWillSavePrefs
    if self._shown_once:
AttributeError: 'NoneType' object has no attribute '_shown_once'
```

Thanks for making this application, so much easier to remove those duplicates from my collection of saved images, just got rid of 110 duplicates (5.5% of my collection)
I was using scripts i wrote that compared meta data, which worked very nicely untiled i needed to compare alt dimensions

**Comment by hsoft** [comment] 2016-08-15 01:17
Thanks for the report @GM-Script-Writer-62850 . I can't reproduce the crash though (even on my 14.04 environment). Does it happen every time you quit dupeGuru?

In the commit referenced above, I make a change that I think would fix the crash. Are you technical enough to build dupeGuru from source? If yes, and if you can reproduce the crash reliably, could you please try to build from `master` and let me know if the crash is fixed?

**Comment by GM-Script-Writer-62850** [comment] 2016-08-15 10:45
depends on how detailed the instructions are
need to make sure i can reproduce it still to verify (seems to work fine ATM), maybe i need to delete the programs configuration data
/home/$USER/.local/share/Hardcoded Software
/home/$USER/.config/Hardcoded Software

this issue came up when i first used the software
** try deleting /home/$USER/.config/Hardcoded Software
scan for pictures and try to exit and click yes

**Comment by arsenetar** [comment] 2022-03-19 23:50
This is a rather old version, I am closing all issues related to 4.0.3 and older as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue.

**Closed by arsenetar** 2022-03-19 23:50 UTC
Labels: bug
