### ISSUE TITLE
Preferences Dialog display issue - Windows 10

### ISSUE THREAD

**Issue by Bmos91** [arsenetar/dupeguru#365] opened 2016-04-28 18:37 UTC
Options text not spacing properly on Windows 10 64bit
![dialog](https://cloud.githubusercontent.com/assets/18725550/14897117/51ab05d6-0d46-11e6-8c78-cc826dd59660.JPG)

**Comment by hsoft** [comment] 2016-04-28 18:47
Relevant note: Windows version of dupeGuru is [currently unmaintained](https://github.com/hsoft/dupeguru#windows-maintainer-wanted)

**Comment by Bmos91** [comment] 2016-04-28 19:15
Ah.  Good to know. Thanks.

**Comment by hsoft** [comment] 2016-04-28 19:21
We don't need to close the issue. Someone *might* step up and revive Windows maintenance. It's just not going to be me.

**Comment by 1kakarot** [comment] 2016-07-14 10:29
Hello everybody.
I have just compiled master branch, in windows 10 64-bit.
Python is 3.5.2 32-bit. I 've installed all packages except cx_Freeze.
I get errors all the time.
I could not reproduce your issue as you can see in the image.
![clipboard01](https://cloud.githubusercontent.com/assets/13013115/16836496/7241f694-49c6-11e6-8ce4-25b2e17a23af.jpg)

I 'll try to become an active contributor.
Thanks.

**Comment by arsenetar** [comment] 2021-08-19 02:40
This is fixed to be best of my knowledge.

**Closed by arsenetar** 2021-08-19 02:40 UTC
Labels: bug, Windows
