### ISSUE TITLE
dupeGuru 4.0.2 crash 

### ISSUE THREAD

**Issue by ziem** [arsenetar/dupeguru#399] opened 2016-11-08 19:54 UTC
```
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.2
Mac OS X Version: Version 10.11.6 (Build 15G1108)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 316, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 766, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 159, in get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 90, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/fs.py", line 257, in get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/fs.py", line 244, in get_file
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/path.py", line 226, in wrapped
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 22, in can_handle
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 15, in is_bundle
NameError: name 'logging' is not defined
```

dupeGuru crashed few times when I tried to find duplicates on HDD drive connected via USB. I unplugged and plugged drive and it solved the problem.

**Comment by jpluimers** [comment] 2016-11-25 17:18
Same here. Probably related that I start searching with an empty list because of #388 hoping the empty list means searching from `/`.

**Comment by roregan** [comment] 2017-01-01 01:13
Seems to be a similar error -- but later versions of both the OS and dupeguru.  AIso am working on an internal drive.

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.12.2 (Build 16C67)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:1350'

**Comment by GarthSnyder** [comment] 2019-02-01 00:12
Same "logging is not defined" error as above, but more recent version of MacOS:

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.14.3 (Build 18D42)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 776, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 159, in get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 90, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/fs.py", line 257, in get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/fs.py", line 244, in get_file
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/path.py", line 226, in wrapped
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 22, in can_handle
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 15, in is_bundle
NameError: name 'logging' is not defined

**Comment by arsenetar** [comment] 2019-12-31 22:55
Duplicate of #389

**Closed by arsenetar** 2019-12-31 22:55 UTC
Labels: bug
