### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by djgrizzyy** [arsenetar/dupeguru#639] opened 2020-04-18 16:00 UTC
# Instructions 
1. Provide a short descriptive title for the issue. A good example is 'Results window appears off screen.', a non-optimal example is 'Problem with App'.
2. Please fill out either the 'Bug / Issue' or the 'Feature Request' section. Replace values in ` `.
3. Delete these instructions and the unused sections.

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.14.5 (Build 18F203)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 105, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 300, in _job_completed
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 279, in _results_changed
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/notify.py", line 33, in notify
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/notify.py", line 72, in dispatch
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/stats_label.py", line 20, in results_changed
AttributeError: 'NoneType' object has no attribute 'refresh'

**Comment by arsenetar** [comment] 2021-08-19 02:30
Duplicate of #396

**Closed as completed by arsenetar** 2021-08-19 02:30 UTC
