### ISSUE TITLE
Crash with "too long path" error

### ISSUE THREAD

**Issue by bobnop31** [arsenetar/dupeguru#740] opened 2020-11-21 18:48 UTC
Application Name: dupeGuru
Version: 4.0.4 RC

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 101, in pulse
  File "core\app.py", line 323, in _job_error
  File "hscommon\jobprogress\performer.py", line 43, in _async_run
  File "core\app.py", line 223, in _do_delete
  File "core\results.py", line 298, in perform_on_marked
  File "core\app.py", line 220, in op
  File "core\app.py", line 236, in _do_delete_dupe
  File "lib\site-packages\send2trash\plat_win.py", line 77, in send2trash
  File "ctypes\__init__.py", line 285, in create_unicode_buffer
ValueError: string too long

**Comment by glubsy** [comment] 2020-11-21 20:20
This should most likely be reported in the [send2trash](https://github.com/arsenetar/send2trash/issues) repository instead. 

It would be nice to have a bit more details as to how to reproduce the bug too. Was there a very long filename in your Results list by any chance?

**Comment by arsenetar** [comment] 2021-03-22 05:38
Duplicate of #854, which had more details provided, also 3rd party and fixed in send2trash.

**Closed as completed by arsenetar** 2021-03-22 05:38 UTC
Labels: bug
