### ISSUE TITLE
during the analysis portion

### ISSUE THREAD

**Issue by nicksjunkyard** [arsenetar/dupeguru#488] opened 2018-02-25 11:56 UTC
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\Users\arsen\github\dupeguru\hscommon\gui\progress_window.py", line 101, in pulse
  File "C:\Users\arsen\github\dupeguru\core\app.py", line 323, in _job_error
  File "C:\Users\arsen\github\dupeguru\hscommon\jobprogress\performer.py", line 43, in _async_run
  File "C:\Users\arsen\github\dupeguru\core\app.py", line 780, in do
  File "C:\Users\arsen\github\dupeguru\core\scanner.py", line 137, in get_dupe_groups
  File "C:\Users\arsen\github\dupeguru\core\pe\scanner.py", line 31, in _getmatches
  File "C:\Users\arsen\github\dupeguru\core\pe\matchblock.py", line 167, in getmatches
  File "C:\Users\arsen\github\dupeguru\core\pe\matchblock.py", line 83, in prepare_pictures
  File "C:\Users\arsen\github\dupeguru\core\pe\photo.py", line 105, in get_blocks
  File "C:\Users\arsen\github\dupeguru\qt\pe\photo.py", line 36, in _plat_get_blocks
TypeError: unorderable types: int() <= str()

**Comment by arsenetar** [comment] 2019-12-31 22:58
Duplicate of #280 Would need more information based on the conversation over there.  Closing this one. Feel free to comment on the other.

**Closed by arsenetar** 2019-12-31 22:58 UTC
