### ISSUE TITLE
Application Crash Mac OS X Big Sur 11.2.2

### ISSUE THREAD

**Issue by 54Rigger** [arsenetar/dupeguru#852] opened 2021-03-04 15:07 UTC
**Describe the bug**
Application Crash 

**To Reproduce**
1. Opened Program
2. Selected Picture mode
3. added Folder from smb network share (hosted on freenas)
4. pressed scan

**Expected behavior**
I expected a list of duplicate files

**Screenshots**
none applicable

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 11.2.2

**Additional context**
Of note,  I had previous success with the identical procedure using a different path for music files 

[dupeguru tracestack.txt](https://github.com/arsenetar/dupeguru/files/6084592/dupeguru.tracestack.txt)

**Comment by arsenetar** [comment] 2021-08-19 02:11
From the attached log this may be fixed in newer versions, I recommend trying the latest version.

**Comment by arsenetar** [comment] 2021-08-22 00:26
Duplicate of #437

**Closed as completed by arsenetar** 2021-08-22 00:26 UTC
Labels: bug
