### ISSUE TITLE
Crashes when I try to dedupe images folder

### ISSUE THREAD

**Issue by viktorbezdek** [arsenetar/dupeguru#759] opened 2021-01-11 11:59 UTC
Crashes after few seconds when I try to dedupe images folder with lots of photos (~30k files, mostly RAWs and JPEGs).

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Verze 10.16 (sestava 20C69)

```
Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 64, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 54, in get_cache
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 38, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 243, in open
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 227, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/dbm/__init__.py", line 94, in open
_dbm.error: [Errno 79] Inappropriate file type or format
```

**Comment by glubsy** [comment] 2021-01-11 14:41
Please use the search feature, this has already been reported and has been fixed in the latest version.

You have several solutions:

1. Use the latest version by building from source.
2. Wait for the latest version (4.1.0) to be packaged and released.
3. If you can't wait, provide help with packaging the MacOS version (see #733 and #753).

Duplicate of #754, #752, #723, #722, #699, #663, #657, #650, #632, #603, #585, #563, #439, #553, #503, #498, #481, #477, #471, #468, #433, #415, #409, #407, #402, #401.

**Comment by qarmin** [comment] 2021-01-12 09:48
Why duplicated issues are not closing?
New version of DupeGuru is already released and there is no need to have this issues opened to pollute issue tracker.

**Comment by glubsy** [comment] 2021-01-12 15:03
I agree. @arsenetar if you need, I can help with bug report triage by closing outdated and obsolete tickets.

**Comment by arsenetar** [comment] 2021-08-19 02:18
Duplicate of #437, closing this one.

**Closed as completed by arsenetar** 2021-08-19 02:18 UTC
Labels: bug
