### ISSUE TITLE
Previously scanned file continues to cause exception on all scans in all locations

### ISSUE THREAD

**Issue by KamillaPup** [arsenetar/dupeguru#889] opened 2021-05-15 07:56 UTC
Ever since I scanned the Nanimoose folder, every scan I have done since then fails with the below exception. I have tried clearing the cache and it still happens. The image in the FAP folder is not in the locations of my scans so I have no idea why that file keeps getting referenced.

```
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.16 (Build 20D91)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Volumes/home/Artwork/Furry/Nanimoose/FAP/Lube_Job_2.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Volumes/home/Artwork/Furry/Nanimoose/FAP/Lube_Job_2.jpg'
```

**Comment by KamillaPup** [comment] 2021-05-15 08:17
I reinstalled it and the error was fixed but thought you would still want the error log.

**Comment by arsenetar** [comment] 2021-08-19 02:16
I recommend trying the latest version there has been some work to correct this issue.

**Comment by arsenetar** [comment] 2021-08-22 00:34
Duplicate of #439.  Clearing the cache via the file menu may help as well.

**Closed as completed by arsenetar** 2021-08-22 00:34 UTC
Labels: bug
