### ISSUE TITLE
Very large program size (bug?) 

### ISSUE THREAD

**Issue by IlluminatiWave** [arsenetar/dupeguru#913] opened 2021-07-06 05:49 UTC
I'll be quick
Control Panel -> Programs -> Uninstall Programs -> Dupeguru

![image](https://user-images.githubusercontent.com/42191299/124548131-e6dd0280-ddf2-11eb-860e-27a12db11d44.png)

Program size is wrongly displayed in windows 11 (22gb?)

Or is there some other folder where Dupeguru saves something?

Potato Specs

Core i5 4200u
Nvidia GTX 840M
12GB ram

Windows 11 (insider official, no beta leaked)
Dupeguru 4.1.1

P.S. I was cleaning my computer and I came across this curiosity so I wanted to know where so much Gigabyte went

**Comment by arsenetar** [comment] 2021-08-07 23:35
I was looking at this on my system (Windows 10) I am seeing the control panel list matches what I would expect.  The installed size matches the size of the directory `C:\Program Files\Hardcoded Software\dupeGuru`.  Perhaps this is a bug in windows 11?

**Comment by arsenetar** [comment] 2022-03-12 11:13
Not able to reproduce this issue in the current version of windows 11, so going to close this, does appear to just be incorrect size reporting in windows.

**Closed as completed by arsenetar** 2022-03-12 11:13 UTC
Labels: bug
