### ISSUE TITLE
Error on MacOS Catalina

### ISSUE THREAD

**Issue by kimneu** [arsenetar/dupeguru#615] opened 2019-12-19 10:14 UTC
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.15.2 (Build 19C57)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Users/kim/Pictures/Photos Library.photoslibrary/originals/7/7E2FDD71-7F21-478D-9DF8-2DED28CBA8A8.jpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Users/kim/Pictures/Photos Library.photoslibrary/originals/7/7E2FDD71-7F21-478D-9DF8-2DED28CBA8A8.jpeg'

**Comment by arsenetar** [comment] 2019-12-31 21:31
I just built new initial binaries for OSX for 4.0.4 which most likely fixes this issue, over at: https://github.com/arsenetar/dupeguru/issues/566#issuecomment-569992117.  If you would like to give one of those a try and let me know if that works that would be helpful. This is most likely a duplicate of #439.

**Closed as completed** 2019-12-31 21:39 UTC
