### ISSUE TITLE
dupeGuru error in application mode "picture" searching in photoslibrary (Mac High Sierra 10.13.2)

### ISSUE THREAD

**Issue by donumcaelo** [arsenetar/dupeguru#478] opened 2018-01-23 09:31 UTC
similar, but not identical to issue #477 
runs trough in application mode (standard), stops i mode "picture" with following traceback:

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.13.2 (Build 17C205)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 64, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 54, in get_cache
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 38, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 243, in open
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 227, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/dbm/__init__.py", line 94, in open
_dbm.error: [Errno 79] Inappropriate file type or format

**Comment by hsoft** [comment] 2018-02-15 02:57
If you try the release linked in #439, does it fix the problem?

**Comment by donumcaelo** [comment] 2018-03-22 15:25
unfortunately not...

**Comment by drumkid0** [comment] 2018-05-16 00:16
Has anyone found a solution yet?

**Comment by arsenetar** [comment] 2019-12-31 22:49
Duplicate of #437

**Closed by arsenetar** 2019-12-31 22:49 UTC
Labels: OSX, bug
