### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by idyclare** [arsenetar/dupeguru#588] opened 2019-08-13 20:35 UTC
# Bug / issue Report
## Description
Dragged 91 folders amounting to 9-10 GB of data into the window and clicked "Explore". The following error was received. These folders had already been "explored" in smaller sets previous to this event (that is, earlier the same day).

## Debug Log
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Versión 10.13.6 (Fase 17G7024)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 774, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 171, in get_folders
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 40, in _get_folders
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 15, in is_bundle
NameError: name 'logging' is not defined

Relevant Console logs:

An error ''' is invalid.' was raised while decoding '('', 'Volumes', 'Wynken - External', 'Restored from Lacey General TM Backups', '2017-12-05-102629', 'Macintosh HD', 'Users', 'tkilgore', 'Library', 'Containers', 'com.apple.share.Video.upload-video-Flickr')'
An error ''' is invalid.' was raised while decoding '('', 'Volumes', 'Wynken - External', 'Restored from Lacey General TM Backups', '2017-12-05-102629', 'Macintosh HD', 'Users', 'tkilgore', 'Library', 'Containers', 'com.apple.share.Video.upload-video-Flickr')'

**Comment by arsenetar** [comment] 2019-12-31 22:56
Duplicate of #389

**Closed as completed by arsenetar** 2019-12-31 22:56 UTC
Labels: bug, macOS
