### ISSUE TITLE
Confirm to cancel

### ISSUE THREAD

**Issue by Zommando** [arsenetar/dupeguru#1033] opened 2022-08-29 06:47 UTC
Please add a feature where you cant accidentally hit cancel by tapping the spacebar when dupe checking by asking if you wish to cancel with a yes or no. 

As of right now there is no safety measure against this.

Losing hours if not days of work by an accidental keystroke can be devastating.

**Comment by arsenetar** [comment] 2022-09-01 05:01
Duplicate of #515

**Closed as completed** 2023-01-06 06:09 UTC
