### ISSUE TITLE
Windows 10 - Error sending marked duplicates to recycle bin

### ISSUE THREAD

**Issue by NotoriousKlein** [arsenetar/dupeguru#920] opened 2021-07-28 04:50 UTC
**Describe the bug**

Windows 10 desktop (intel NUC10i5).  

**To Reproduce**

1) Scanned two drives for duplicates:

Drive 1 = Local USB drive, formatted ExFat
Drive 2= Mapped Network Drive (Synology NAS)

2)  Marked all dupes
3)  Sent all marked items to Recycle Bin
4)  Error message popped up

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version [e.g. 4.1.0]:    10.0.19043.1147

**Additional context**

Application Name: dupeGuru
Version: 4.1.1

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 105, in pulse
  File "core\app.py", line 347, in _job_error
  File "hscommon\jobprogress\performer.py", line 45, in _async_run
  File "core\app.py", line 243, in _do_delete
  File "core\results.py", line 316, in perform_on_marked
  File "core\app.py", line 238, in op
  File "core\app.py", line 256, in _do_delete_dupe
  File "send2trash\plat_win.py", line 77, in send2trash
  File "ctypes\__init__.py", line 291, in create_unicode_buffer
ValueError: string too long

**Comment by glubsy** [comment] 2021-07-28 14:21
Thanks for the report. Might be a bug in [send2trash](https://github.com/arsenetar/send2trash). 

Looks like either a file name was too long.

**Comment by arsenetar** [comment] 2021-07-31 01:13
This is a duplicate of #854 which is a bug that has been fixed in send2trash.  This will need a new release to bring in the newer version of send2trash.

**Comment by arsenetar** [comment] 2021-07-31 01:14
Closing due to duplicate.

**Closed as completed by arsenetar** 2021-07-31 01:14 UTC
Labels: bug, Windows, 3rd party
