### ISSUE TITLE
'NoneType' object has no attribute 'ref' during make_selected_reference

### ISSUE THREAD

**Issue by pogowolf** [arsenetar/dupeguru#290] opened 2015-03-27 19:25 UTC
```
Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "C:\src\dupeguru\core\app.py", line 553, in make_selected_reference
  File "C:\src\dupeguru\core\app.py", line 767, in without_ref
  File "C:\src\dupeguru\core\app.py", line 767, in <listcomp>
AttributeError: 'NoneType' object has no attribute 'ref'
```

I believe I clicked 'cancel' and somehow the reference was removed.

![untitled picture](https://cloud.githubusercontent.com/assets/1815756/6875485/5b00cc46-d495-11e4-998f-b613e7446809.png)

Notice the middle line in the screen shot

**Comment by hsoft** [comment] 2015-03-27 21:29
Thanks. I've seen this crash log before but I've never been able to reproduce it. This is the closest we are to reliable reproduction.

I have a question though: What do you mean by "I believe I clicked 'cancel'"? Cancel what, a second scan? Were you in the middle of a second scan (because we can see that you already have results), which you cancelled?

**Comment by arsenetar** [comment] 2022-03-19 23:48
This is a rather old version, I am closing all issues related to 4.0.3 and older as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue.

**Closed by arsenetar** 2022-03-19 23:48 UTC
Labels: bug
