### ISSUE TITLE
Application Name: dupeGuru Version: 4.0.3  Traceback (most recent call last):   File "C:\Users\arsen\github\dupeguru\hscommon\gui\progress_window.py", line 96, in pulse   File "C:\Users\arsen\github\dupeguru\qtlib\progress_window.py", line 44, in close AttributeError: 'ProgressWindow' object has no attribute '_timer'

### ISSUE THREAD

**Issue by cbimcb** [arsenetar/dupeguru#573] opened 2019-05-31 02:56 UTC
Application Name: dupeGuru
Version: 4.0.3

Traceback (most recent call last):
  File "C:\Users\arsen\github\dupeguru\hscommon\gui\progress_window.py", line 96, in pulse
  File "C:\Users\arsen\github\dupeguru\qtlib\progress_window.py", line 44, in close
AttributeError: 'ProgressWindow' object has no attribute '_timer'

**Comment by arsenetar** [comment] 2019-05-31 04:43
Duplicate of #449 fixed in the current windows version 4.0.4.

**Closed as completed by arsenetar** 2019-05-31 04:43 UTC
