### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by steven5554** [arsenetar/dupeguru#650] opened 2020-04-30 15:46 UTC
# Instructions 
1. Provide a short descriptive title for the issue. A good example is 'Results window appears off screen.', a non-optimal example is 'Problem with App'.
2. Please fill out either the 'Bug / Issue' or the 'Feature Request' section. Replace values in ` `.
3. Delete these instructions and the unused sections.

# Bug / issue Report
System Information:
 - DupeGuru Version: `version`
 - Operating System: `Windows/Linux/OSX` `distribution` `version` 

If using the source distribution and building yourself also provide (otherwise remove):
 - Python Version: `version ex. 3.6.6` `32/64bit`  
 - Complier: `gcc/llvm/msvc` `version`

## Description
`Provide a detailed description of the issue to help reproduce it.  If it happens after a specific sequence of events provide them here.`

## Debug Log
```
If reporting an error provide the debug log and/or the error message information.  If the debug log is short < 40 lines you can provide it here, otherwise attach the text file to this issue.
```

# Feature Requests
`Provide a detailed description of the feature.`

**Comment by steven5554** [comment] 2020-04-30 15:47
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Versie 10.15.4 (build 19E287)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:34228'

**Comment by glubsy** [comment] 2020-05-07 13:26
Please edit your first post and replace the appropriate fields with relevant information.

**Comment by arsenetar** [comment] 2021-08-22 00:30
Duplicate of #439

**Closed as completed by arsenetar** 2021-08-22 00:30 UTC
