### ISSUE TITLE
int and fraction not support in picture scan

### ISSUE THREAD

**Issue by Roseline2005** [arsenetar/dupeguru#939] opened 2021-09-07 17:19 UTC
**Describe the bug**
an error in the instantces of int and fraction

**To Reproduce**
i tried scanning a large folder with more then 4k images and i got the error code 
TypeError: '<=' not supported between instances of 'int' and 'Fraction' but when i try with standard it is fine

**Expected behavior**
i hope it could be fixed with large file count

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version21h1

**Additional context**
 [df.txt](https://github.com/arsenetar/dupeguru/files/7123283/df.txt)

**Comment by arsenetar** [comment] 2021-09-16 01:10
Duplicate of #551, has been fixed.

**Closed as completed by arsenetar** 2021-09-16 01:10 UTC
Labels: bug
