### ISSUE TITLE
issue wenn I use dupe guru to find duplicated photographic

### ISSUE THREAD

**Issue by Razorback5581** [arsenetar/dupeguru#497] opened 2018-03-29 10:55 UTC
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.11.6 (assemblage 15G19009)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Users/gunterfoerster/Pictures/dossier 60 ans Ninone/Mes 60 ans  Ninone 19-20 mars 2011 (original).aplibrary/Masters/2012/02/05/20120205-233301/DSC_0221_7.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Users/gunterfoerster/Pictures/dossier 60 ans Ninone/Mes 60 ans  Ninone 19-20 mars 2011 (original).aplibrary/Masters/2012/02/05/20120205-233301/DSC_0221_7.jpg'

**Comment by Cebtenzzre** [comment] 2018-05-12 11:40
This should probably be re-titled to something like "[PE] KeyError in getitem".

**Comment by arsenetar** [comment] 2019-12-31 22:32
This seems to be a duplicate of #439 

I just built new initial binaries for OSX for 4.0.4 which most likely fixes this issue, over at: #566 (comment). If you would like to give one of those a try and let me know if that works that would be helpful.

**Closed** 2019-12-31 23:04 UTC
Labels: OSX, bug
