### ISSUE TITLE
Tech... disabled

### ISSUE THREAD

**Issue by laingpj** [arsenetar/dupeguru#846] opened 2021-02-10 23:42 UTC
Worked this morning and now when I run, I get this error.  Uninstalled and reinstalled, searched for the culprit file (not there from what I can tell), so I am stumped.  Doesn't take much.

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.16 (Build 20D64)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Users/plaing/Pictures/Photos Library.photoslibrary/originals/8/844D8B7A-0F74-479A-B7F7-0D8F8D9BA616.jpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Users/plaing/Pictures/Photos Library.photoslibrary/originals/8/844D8B7A-0F74-479A-B7F7-0D8F8D9BA616.jpeg'

**Comment by arsenetar** [comment] 2021-08-19 02:15
I recommend trying the latest version there has been some work to correct this issue.

**Comment by arsenetar** [comment] 2021-08-22 00:33
Duplicate of #439. Clearing the cache via the file menu may also help.

**Closed as completed by arsenetar** 2021-08-22 00:33 UTC
Labels: bug
