### ISSUE TITLE
Repeatedly crashing while scanning ext HD (macOS 11.3.1)

### ISSUE THREAD

**Issue by adamsaltman** [arsenetar/dupeguru#896] opened 2021-05-21 12:12 UTC
Scanned a 4TB ext HD (ext4 formatted, using extFS kernel ext) just fine, but when scanning a 2TB ext HD (also ext4 via extFS) now crashes multiple times. Have checked the disk and no errors. 

**To Reproduce**
Start dupeGuru
Select disk (/Volumes/TempHD)
Select application mode Pictures, scan type Content
Click Scan
Crash after about 15 minutes of working

**Desktop (please complete the following information):**
 - OS: macOS 11.3.1 on a 2020 mac mini M1 8GB/512GB
 - dupeGuru 4.0.3

**Error report**
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.16 (Build 20E241)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:295692'

**Comment by glubsy** [comment] 2021-06-21 23:50
This is fixed in recent versions.

**Comment by arsenetar** [comment] 2021-06-22 03:33
@adamsaltman I would encourage you to try out one of the two builds available over at https://github.com/arsenetar/dupeguru/issues/761#issuecomment-814582895 as many of the 4.0.3 issues have been fixed in the last few releases.

**Comment by arsenetar** [comment] 2021-08-19 01:58
@adamsaltman The latest release (https://github.com/arsenetar/dupeguru/releases/latest) has built packages, I believe it should fix this issue as noted.

**Comment by arsenetar** [comment] 2021-08-22 00:34
Duplicate of #439

**Closed as completed by arsenetar** 2021-08-22 00:34 UTC
Labels: bug
