### ISSUE TITLE
empty files not seen as duplicates

### ISSUE THREAD

**Issue by iweindesmedt** [arsenetar/dupeguru#321] opened 2015-08-22 20:53 UTC
empty files (created with e.g. `touch empty.txt`) are not getting marked as duplicates.
is this done intentionally?

**Comment by hsoft** [comment] 2015-08-23 18:10
Did you try disabling the option for ignoring small files? I'd have to look in the code, but I don't think that dupeGuru explicitly ignores 0-sized files. I think that only the small-files-ignore preference can be the cause of this.

In any case, it's a good candidate for a FAQ entry.

**Comment by iweindesmedt** [comment] 2015-08-23 19:31
yes, it is disabled
![screen shot 2015-08-23 at 21 29 39](https://cloud.githubusercontent.com/assets/812033/9429833/26b7174c-49de-11e5-8c3f-9ed57e87a9c0.png)

**Comment by arsenetar** [comment] 2021-08-28 23:17
Fixed in e22d7d2fc90922125f162e5bb11fb2abed92eb59

**Closed** 2021-08-28 23:17 UTC
Labels: docs
