### ISSUE TITLE
Photo deduping with dupeGuru

### ISSUE THREAD

**Issue by mccarmich** [arsenetar/dupeguru#752] opened 2020-12-20 17:09 UTC
After having done one successful scan, which found thousands of dupes, I noticed it had missed some where there were multiple dupes--so I reran the scan, it crashed a couple of times, with this message:

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.13.6 (Build 17G66)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:278357'

Relevant Console logs:

Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/g/gk/gkWX5P3bTwCd72cUssvyNA
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/t
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/t/tp
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/t/tp/TPO2S1eIQhKn9fVj6MuKpQ
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/t/t8
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/t/t8/T8mGmkZURM27szmVtueG%A
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/o
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/o/on
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/o/on/onWXrtTmRc+7HvbTHNoZOQ
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/h
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/h/hb
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/h/hb/HBAyGNuUSvyCDTVQABXBnA
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/q
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/q/qc
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/q/qc/qC0tD4TvQmKMHLg4fe4JFQ
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/3
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/3/3d
Collected 0 files in folder /Users/michellebeck/Pictures/Photos Library.photoslibrary/Attachments/3/3d/3dCuw2H2TNKMxTgGfek%4Q
Scanning 676159 files
Getting matches. Scan type: 10

**Comment by glubsy** [comment] 2020-12-20 18:12
Please use the search feature, this has already been reported and has been fixed in the latest version.

You have several solutions:
1. Use the [latest version](https://github.com/glubsy/dupeguru/tree/dev) by building from source.
2. Wait for the latest version (4.1.0) to be packaged and released.
3. If you can't wait, provide help with packaging the MacOS version (see #733).

Duplicate of #723, #722, #699, #663, #657, #650, #632, #603, #585, #563, #439, #553, #503, #498, #481, #477, #471, #468, #433, #415, #409, #407, #402, #401.

**Closed as completed** 2021-08-08 01:05 UTC
Labels: bug
