### ISSUE TITLE
Laptop went unresposive during scan

### ISSUE THREAD

**Issue by dbooth914** [arsenetar/dupeguru#407] opened 2017-02-02 01:53 UTC
I had set my laptop down on the floor while it was scanning iphoto library, and when I picked it up it went dark screen, which may be an issue with the laptop, not the app. I had to do a hard reset with the power button and now dupeguru throws this error after starting the scan. I reinstalled and it still throws the error. I will try an uninstall, reboot and re-install (can you tell i'm a Windows guy?) and update this ticket. 

I moved dupeguru to the trash and then reinstalled from the .dmg file. The issue persists. 

Next try, I moved dupeguru to the trash, emptied the trash, rebooted and reinstalled. I don't know how the Macs uninstall, but the setting for which folder to scan was retained thru the uninstall/reinstall. The app still crashes when scanning the iphoto directory using the photos tab in the app. However, i forgot to select photos and it went ahead and did the standard scan and found the duplicate as files. 

That's it. If I find more to add, I'll revisit the ticket. HTH.

Thanks for the app!

--Doug

More info: Standard scan works, Picture scan works but only for Exif. Different number of dupes found using those two scans. Standard/Contents 3065-9.42GB & Pictures/Exif 2370 4.2GB

 
------------------
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.8.5 (Build 12F2560)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:6932'

**Comment by arsenetar** [comment] 2019-12-31 23:01
Duplicate of #439, should be fixed in 4.0.4

**Closed by arsenetar** 2019-12-31 23:01 UTC
Labels: bug
