### ISSUE TITLE
dupeguru PE: preferences dialog cannot be dragged with dupes list open

### ISSUE THREAD

**Issue by deutrino** [arsenetar/dupeguru#350] opened 2016-03-12 18:10 UTC
**WHAT ACTUALLY HAPPENS**
1. Search for some dupes.
2. Dupes list opens.
3. Click View > Preferences
4. Preferences dialog opens.
5. Clicking and dragging to move the dialog instead moves the dupes window.

**WHAT I EXPECT TO HAPPEN**

The dialog should be draggable.

**SYSTEM INFO**

Linux Mint 17.3, amd64, running Cinnamon.

Thanks for your hard work on dupeGuru, it's been incredibly useful to me.

**Comment by hsoft** [comment] 2016-03-12 18:41
The Preference dialog is opened as a modal window. I use i3, albeit not a common use case and I can't reproduce the issue (dragging the preference window actually drags the preference window). I also can't reproduce this in Ubuntu 14.04. Could that issue be Cinnamon-specific?

**Comment by gordon-morehouse** [comment] 2016-03-12 19:12
I'm uncertain. I know somebody who I believe is running Mint+Xfce, so I'll try to test it on his machine.

**Comment by gordon-morehouse** [comment] 2016-03-12 19:16
This issue also occurs on the Re-Prioritize Results dialog.

**Comment by arsenetar** [comment] 2021-08-07 23:54
dupeGuru PE is an old version, likely this may behave differently in the combined version.  Have not noticed this issue in recent builds in Windows/macOS/Ubuntu/debian.  Closing this, if issue still exists in latest version this may be reopened.

**Closed by arsenetar** 2021-08-07 23:54 UTC
Labels: bug
