### ISSUE TITLE
Fails to load pictures directory under Mac OS "Catalina", addendum to #585

### ISSUE THREAD

**Issue by pcolsen** [arsenetar/dupeguru#603] opened 2019-10-25 15:29 UTC
I reported this failure under Mojave.  The failure appears to be identical under Catalina.  I would have added this to the previous report, but I couldn't.  I've added a small amount of additional information

Here's the additional information.

I didn't report the details of the display when the program fails.

When I press "scan: a window pops-up with a blue progress bar.  Sometimes the program fails immediately.  Other times the bars quickly grays out and the label "Collecting files to scan appears".  The program then fails either immediately or within a very short time.  No blue appears in the progress bar.  

Here are the contents of the error window.

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.15 (Build 19A602)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:53039'

Relevant Console logs:

Collected 0 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM
Collected 40 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/149CANON
Collected 96 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/153CANON
Collected 91 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/145CANON
Collected 97 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/144CANON
Collected 97 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/152CANON
Collected 101 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/148CANON
Collected 103 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/155CANON
Collected 99 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/143CANON
Collected 92 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/142CANON
Collected 104 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/154CANON
Collected 102 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/157CANON
Collected 44 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/156CANON
Collected 0 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/CANONMSC
Collected 100 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/147CANON
Collected 101 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/151CANON
Collected 96 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/150CANON
Collected 99 files in folder /Users/pcolsen/Pictures/Compact_memory_card_transferred_2019_04_23/DCIM/146CANON
Scanning 2670 files
Getting matches. Scan type: 10

**Comment by blackfrank74** [comment] 2019-11-03 01:41
I did a high level compare and get seemingly the same error message.

Application mode = pictures
scan type = contents

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.15 (Build 19A602)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Users/fs/Pictures/2014/12/19/Events - 6462.JPG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Users/fs/Pictures/2014/12/19/Events - 6462.JPG'

**Comment by arsenetar** [comment] 2019-12-31 21:39
Duplicate to #585.

I just built new initial binaries for OSX for 4.0.4 which most likely fixes this issue, over at: https://github.com/arsenetar/dupeguru/issues/566#issuecomment-569992117.  If you would like to give one of those a try and let me know if that works that would be helpful. This is most likely a duplicate of #439.

**Closed as completed by arsenetar** 2019-12-31 21:39 UTC
