### ISSUE TITLE
Crashed when attempting to check dups on fairly large set of folders

### ISSUE THREAD

**Issue by mlevison** [arsenetar/dupeguru#496] opened 2018-03-26 01:28 UTC
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.13.3 (Build 17D102)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 776, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 159, in get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 100, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/directories.py", line 90, in _get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/fs.py", line 257, in get_files
  File "build/dupeGuru.app/Contents/Resources/py/core/fs.py", line 244, in get_file
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/path.py", line 226, in wrapped
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 22, in can_handle
  File "build/dupeGuru.app/Contents/Resources/py/inter/directories.py", line 15, in is_bundle
NameError: name 'logging' is not defined

**Comment by arsenetar** [comment] 2019-12-31 22:56
Duplicate of #389

**Closed by arsenetar** 2019-12-31 22:56 UTC
Labels: OSX
