### ISSUE TITLE
Crash on BigSur when trying to scan Pictures with DupeGuru

### ISSUE THREAD

**Issue by isotronik** [arsenetar/dupeguru#856] opened 2021-03-13 09:45 UTC
**Describe the bug**
Just setting application to Pictures and scantyp to content starting the scan leads to this Message:

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.16 (Build 20D80)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 64, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 54, in get_cache
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 38, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 243, in open
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 227, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/dbm/__init__.py", line 94, in open
_dbm.error: [Errno 79] Inappropriate file type or format

**To Reproduce**
As described in the first sentence

**Expected behavior**
Scanning the directories

**Screenshots**
none

**Desktop (please complete the following information):**
  Systemversion:	macOS 11.2.2 (20D80)
  Kernel-Version:	Darwin 20.3.0

**Comment by mail2bipo** [comment] 2021-03-19 21:56
Hi Isotronik,
You're not alone with the same bug:

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.16 (assemblage 20D91)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 64, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 54, in get_cache
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 38, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 243, in open
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 227, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/dbm/__init__.py", line 94, in open
_dbm.error: [Errno 79] Inappropriate file type or format

Hope someone can help. I can't, sorry.

Cheers,
Bipo

**Comment by arsenetar** [comment] 2021-08-19 02:13
From the logs here, I recommend trying the latest version as this is believed to have been fixed.

**Comment by arsenetar** [comment] 2021-08-19 02:18
Duplicate of #437, closing this one.

**Closed as completed by arsenetar** 2021-08-19 02:18 UTC
Labels: bug
