### ISSUE TITLE
NotImplementedError when loading a results file

### ISSUE THREAD

**Issue by heirung** [arsenetar/dupeguru#319] opened 2015-07-21 18:04 UTC
I opened a (pretty large -- 317 KiB) results file from a folder scan, and dupeGuru crashed after the bar had reached 100 %. Here is the whole traceback: (it ends kind of abruptly):

```
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 3.9.1
Mac OS X Version: Version 10.9.5 (Build 13F1096)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/inter/result_table.py", line 25, in isDeltaAtRow_column_
  File "build/dupeGuru.app/Contents/Resources/py/core/gui/result_table.py", line 43, in is_cell_delta
  File "build/dupeGuru.app/Contents/Resources/py/core/fs.py", line 168, in get_display_info
NotImplementedError

Relevant Console logs:

Exception on GetDisplayInfo for /Volumes/WD Elements 1 TB/WD Combo Copy/Rippet musikk/Big Star/#1 Record: 
Exception on GetDisplayInfo for /Volumes/WD Elements 1 TB/Original/Rippet musikk/Big Star/#1 Record: 
Exception on GetDisplayInfo for /Volumes/WD Elements 1 TB/WD Combo Copy/Rippet musikk/Big Star/#1 Record: 
Exception on GetDisplayInfo for /Volumes/WD Elements 1 TB/WD Combo Copy/Backup Vista/Mine dok 8. juli 09/My Music/iTunes/iTunes Music/Big Star/#1 Record: 
Exception on GetDisplayInfo for /Volumes/WD Elements 1 TB/WD Combo Copy/Backup Vista/Mine dok 8. juli 09/My Music/iTunes/iTunes Music/Big Star/#1 Record: 
```

**Comment by giopas** [comment] 2015-12-09 19:52
Hi,

I have scanned a folder on my NAS (using my Win10 desktop and DupeGuru PE 2.10.1) to find duplicate images and after almost a day of work I get the full list.

The problem is that I have saved the list in .dupeguru format (it is 11 MB) and it is not loading.

I still don't know if it crashed but it is taking almost 20 minutes now... Is it a known problem? Is there any results size limit? DGPE is taking only 32.6 MB of RAM and 0% of CPU so I think it just "gave up" loading results...

**Comment by patrickatamaniuk** [comment] 2015-12-12 23:12
large result lists take long time to load. Loading currently requires some calculation and cross-checking. Give it some hours. My 5MB results take a good half an hour to load, but eventually it loaded.

**Comment by arsenetar** [comment] 2022-03-19 23:49
This is a rather old version, I am closing all issues related to 4.0.3 and older as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue.

**Closed by arsenetar** 2022-03-19 23:49 UTC
Labels: bug
