### ISSUE TITLE
PPA won't load in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by cbitterfield** [arsenetar/dupeguru#610] opened 2019-12-11 03:13 UTC
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/hsoft/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by arsenetar** [comment] 2019-12-11 03:22
Try the updated packages at: https://launchpad.net/~dupeguru/+archive/ubuntu/ppa

**Comment by arsenetar** [comment] 2019-12-11 03:30
Duplicate of #484

**Closed as completed by arsenetar** 2019-12-11 03:30 UTC
