### ISSUE TITLE
Paths containing pound sign incompatible with dupeguru

### ISSUE THREAD

**Issue by JustinReinhart** [arsenetar/dupeguru#548] opened 2019-01-16 21:07 UTC
Bug: If you drag-and-drop a folder from Windows Explorer where a pound sign # (aka hashtag aka octothorpe) is present in the path, dupeGuru truncates the path that is imported and targets the incorrect folder or even targets the entire drive by mistake.

Example:
1. User drags in folder d:\Dropbox_Runoff\#Process-these-files .  (Please note there is a backslash right before the pound sign in this example but github is hiding it. The subfolder is called #Process-these-files.)
2. Bug: dupeGuru adds d:\Dropbox_Runoff to the list, ignoring the next subfolder. User intended to add d:\Dropbox_Runoff\#Process-these-files. 

If you do this on the drive root, for example by dragging in d:\#Process , then dupeGuru will ignore it and incorrectly target d:\ .  Furthermore, dragging in a path containing a pound sign can also destroy the list of folders already present and replace them with a single incorrect path in the list. 

I'm using Windows 7.  DupeGuru 4.0.3.  Pound sign is a valid supported character in filenames in Windows.

**Comment by Dobatymo** [comment] 2019-05-29 03:13
I can reproduce that with DupeGuru 4.0.4 Windows 10 x64.

**Comment by arsenetar** [comment] 2021-08-28 22:40
This was fixed in 2c9437bef4c51fbee726920c583efcccd52cc349

**Closed by arsenetar** 2021-08-28 22:40 UTC
