### ISSUE TITLE
Crash on startup on Ubuntu 20.04

### ISSUE THREAD

**Issue by Valeryan24** [arsenetar/dupeguru#637] opened 2020-04-11 16:45 UTC
Hi, I just installed DupeGuru with the Ubuntu ppa - https://launchpad.net/~dupeguru/+archive/ubuntu/ppa - on the development version 20.04 LTS.

But program doesn't launch, here is the error message :

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Gdk-Message: 18:41:40.726: Window 0x209b220 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 18:41:40.726: Window 0x209b220 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 18:41:40.726: Window 0x209b220 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 18:41:40.726: Window 0x209b220 is a temporary window without parent, application will not be able to position it on screen.
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/dupeguru", line 66, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 24, in <module>
    from . import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from . import block, cache, exif, iphoto_plist, matchblock, matchexif, photo, prioritize, result_table, scanner # noqa
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from ._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2 # NOQA
ModuleNotFoundError: No module named 'core.pe._block'

https://framapic.org/V0Mwt71yWUPq/nKkKQ0meHsr5.png
https://framapic.org/lYvGBlydaTrK/FrI6fXBeRpOe.png

Thanks in advance for your help !

**Comment by travistabbal** [comment] 2020-04-15 14:01
I found this in another bug report here. These commands create some file links that newer Ubuntu releases seem to need. 


sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-36m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-37m-x86_64-linux-gnu.so

sudo ln /usr/share/dupeguru/core/pe/_block.cpython-36m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-37m-x86_64-linux-gnu.so

sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-36m-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-37m-x86_64-linux-gnu.so

**Comment by Akuukis** [comment] 2020-04-15 14:11
I also tried dupeguru PPA on Ubuntu 20.04, and it wont start. Here's the output:

```
$ cat /etc/apt/sources.list.d/dupeguru-ubuntu-ppa-bionic.list
deb http://ppa.launchpad.net/dupeguru/ppa/ubuntu bionic main
$ sudo apt update
...
$ sudo apt install dupeguru
...
$ dupeguru
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/dupeguru", line 66, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 24, in <module>
    from . import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from . import block, cache, exif, iphoto_plist, matchblock, matchexif, photo, prioritize, result_table, scanner # noqa
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from ._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2 # NOQA
ModuleNotFoundError: No module named 'core.pe._block'
```
I tried above-mentioned linking but nothing changed.

Building from source works, see here https://github.com/arsenetar/dupeguru/issues/620#issuecomment-614070696.

**Comment by GM-Script-Writer-62850** [comment] 2020-04-16 04:59
I managed to compile it on xubuntu 20.04 64bit, once you cd into the folder run 'make run'
http://www.mediafire.com/file/1urcebya68i2kc0/dupeguru-master_build_2020-04-16.tar.gz/file
do not expect audio files to process, i could not get the dependency to work

**Comment by aeirado** [comment] 2020-04-21 19:47
Hi, dupeguru works for me on Ubuntu 20.04, but I got un error when I did the build with "make":

`
Building wheel for hsaudiotag3k (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/andre/dupeguru/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f7bugcjv/hsaudiotag3k/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f7bugcjv/hsaudiotag3k/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ah46zl16
       cwd: /tmp/pip-install-f7bugcjv/hsaudiotag3k/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for hsaudiotag3k
`


Any one know what this mean?
Thanks!

**Comment by GM-Script-Writer-62850** [comment] 2020-04-22 00:43
I think it is something that is required for comparing audio files, i assume without that part compiling audio comparison will be broke

**Comment by GM-Script-Writer-62850** [comment] 2020-04-25 00:40
Command to install dependencies to compile on 20.04
```
sudo apt-get install build-essential python3-send2trash python3-sphinx python3-polib python3-pytest python3-flake8 black python3-pyqt5 python3-venv gettext python3-dev pyqt5-dev-tools python3-pip
```
at this point you can run `make` and `make run`

**Comment by GM-Script-Writer-62850** [comment] 2020-04-25 01:04
Also managed to make the pre-built deb work
deb file: https://launchpad.net/~hsoft/+archive/ubuntu/ppa/+build/11261317/+files/dupeguru_4.0.3~xenial_amd64.deb
```
sudo ln -s _block.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-38-x86_64-linux-gnu.so
sudo ln -s _cache.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-38-x86_64-linux-gnu.so
sudo ln -s _block_qt.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-38-x86_64-linux-gnu.so
```

**Comment by greydmiyu** [comment] 2020-07-07 09:16
Above links are not working here with the referenced Deb.

grey@morpheus ~ % dupeguru
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/dupeguru", line 66, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 37, in <module>
    from .pe.photo import File as PlatSpecificPhoto
  File "/usr/share/dupeguru/qt/pe/photo.py", line 13, in <module>
    from .block import getblocks
  File "/usr/share/dupeguru/qt/pe/block.py", line 9, in <module>
    from ._block_qt import getblocks # NOQA
ModuleNotFoundError: No module named 'qt.pe._block_qt'

**Comment by GM-Script-Writer-62850** [comment] 2020-07-07 13:10
What do you have in these folders?
```
$ ls -l  /usr/share/dupeguru/{core,qt}/pe/
/usr/share/dupeguru/core/pe/:
total 128
-rw-r--r-- 2 root root 11072 Nov 26  2016 _block.cpython-35m-x86_64-linux-gnu.so
-rw-r--r-- 2 root root 11072 Nov 26  2016 _block.cpython-36m-x86_64-linux-gnu.so
lrwxrwxrwx 1 root root    38 May 10 17:32 _block.cpython-38-x86_64-linux-gnu.so -> _block.cpython-35m-x86_64-linux-gnu.so
-rw-r--r-- 1 root root  4401 Nov 26  2016 block.py
-rw-r--r-- 2 root root 10400 Nov 26  2016 _cache.cpython-35m-x86_64-linux-gnu.so
-rw-r--r-- 2 root root 10400 Nov 26  2016 _cache.cpython-36m-x86_64-linux-gnu.so
lrwxrwxrwx 1 root root    38 May 10 17:32 _cache.cpython-38-x86_64-linux-gnu.so -> _cache.cpython-35m-x86_64-linux-gnu.so
-rw-r--r-- 1 root root   908 Nov 26  2016 cache.py
-rw-r--r-- 1 root root  3870 Nov 26  2016 cache_shelve.py
-rw-r--r-- 1 root root  5162 Nov 26  2016 cache_sqlite.py
-rw-r--r-- 1 root root 10797 Nov 26  2016 exif.py
-rw-r--r-- 1 root root   119 Nov 26  2016 __init__.py
-rw-r--r-- 1 root root  1093 Nov 26  2016 iphoto_plist.py
-rw-r--r-- 1 root root 10791 Nov 26  2016 matchblock.py
-rw-r--r-- 1 root root  1137 Nov 26  2016 matchexif.py
-rw-r--r-- 1 root root  3930 Nov 26  2016 photo.py
-rw-r--r-- 1 root root   904 Nov 26  2016 prioritize.py
drwxr-xr-x 2 root root  4096 Apr 30  2018 __pycache__
-rw-r--r-- 1 root root  1226 Nov 26  2016 result_table.py
-rw-r--r-- 1 root root  1199 Nov 26  2016 scanner.py

/usr/share/dupeguru/qt/pe/:
total 52
-rw-r--r-- 1 root root  1556 Nov 26  2016 block.py
-rw-r--r-- 2 root root 10400 Nov 26  2016 _block_qt.cpython-35m-x86_64-linux-gnu.so
-rw-r--r-- 2 root root 10400 Nov 26  2016 _block_qt.cpython-36m-x86_64-linux-gnu.so
lrwxrwxrwx 1 root root    41 May 10 17:32 _block_qt.cpython-38-x86_64-linux-gnu.so -> _block_qt.cpython-35m-x86_64-linux-gnu.so
-rw-r--r-- 1 root root  4338 Nov 26  2016 details_dialog.py
-rw-r--r-- 1 root root     0 Nov 26  2016 __init__.py
-rw-r--r-- 1 root root  2152 Nov 26  2016 photo.py
-rw-r--r-- 1 root root  2505 Nov 26  2016 preferences_dialog.py
drwxr-xr-x 2 root root  4096 Apr 30  2018 __pycache__
-rw-r--r-- 1 root root   890 Nov 26  2016 results_model.py
```

**Comment by greydmiyu** [comment] 2020-07-10 09:32
False alarm.  I had installed a 4.04 package and the links were conflicting with what that had installed.  My apologies.

**Comment by r0o-one** [comment] 2020-07-25 16:57
It works on ubuntu 20.4 lts, don't upgrade to 4.0.4 because it stops working.

> Also managed to make the pre-built deb work
> deb file: https://launchpad.net/~hsoft/+archive/ubuntu/ppa/+build/11261317/+files/dupeguru_4.0.3~xenial_amd64.deb
> 
> ```
> sudo ln -s _block.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-38-x86_64-linux-gnu.so
> sudo ln -s _cache.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-38-x86_64-linux-gnu.so
> sudo ln -s _block_qt.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-38-x86_64-linux-gnu.so
> ```

**Comment by Bzzz** [comment] 2020-12-19 19:55
Symlinking on 20.04 doesn't really work with both 4.03 and 4.04 versions. Also building from scratch (github sources) leads to a partial crash after the build somehow succeeds with the audio part failing. That one can be avoided by running pip3 install hsaudiotag3k (and probably wheel?) prior to the make command, but doesn't change the second error.

```  ERROR: Command errored out with exit status 1:
   command: /tmp/dupeguru/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q9ctl4z0/hsaudiotag3k/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q9ctl4z0/hsaudiotag3k/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-d3jygd99                                                                          
       cwd: /tmp/pip-install-q9ctl4z0/hsaudiotag3k/                                                                                                                  
  Complete output (8 lines):                                                                                                                                         
  /tmp/dupeguru/env/lib/python3.8/site-packages/setuptools/dist.py:473: UserWarning: Normalizing '1.1.3-1' to '1.1.3.post1'                                          
    warnings.warn(                                                                                                                                                   
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]                                                                                              
     or: setup.py --help [cmd1 cmd2 ...]                                                                                                                             
     or: setup.py --help-commands                                                                                                                                    
     or: setup.py cmd --help                                                                                                                                         
                                                                                                                                                                     
  error: invalid command 'bdist_wheel'                                                                                                                               
  ----------------------------------------                                                                                                                           
  ERROR: Failed building wheel for hsaudiotag3k
```
after which the GUI opens fine and even remembers folders back from the working 18.04 installation. After comparing an image folder, this one shows up right before where the results would have been displayed. 
```Application Name: dupeGuru
Version: 4.0.4

Traceback (most recent call last):
  File "/tmp/dupeguru/hscommon/gui/progress_window.py", line 109, in pulse
    self._finish_func(self.jobid)
  File "/tmp/dupeguru/core/app.py", line 316, in _job_completed
    self.view.show_results_window()
  File "/tmp/dupeguru/qt/app.py", line 362, in show_results_window
    self.showResultsWindow()
  File "/tmp/dupeguru/qt/app.py", line 226, in showResultsWindow
    self.main_window.showTab(self.resultWindow)
  File "/tmp/dupeguru/qt/tabbed_window.py", line 176, in showTab
    self.setTabVisible(index, True)
  File "/tmp/dupeguru/qt/tabbed_window.py", line 186, in setTabVisible
    return self.tabWidget.setTabVisible(index, value)
AttributeError: 'QTabWidget' object has no attribute 'setTabVisible'
``

**Comment by glubsy** [comment] 2020-12-19 20:41
> AttributeError: 'QTabWidget' object has no attribute 'setTabVisible'

This has been fixed in a merge request. Use this [4.1.0 branch](https://github.com/glubsy/dupeguru/tree/dev) instead, it should work.

**Comment by Bzzz** [comment] 2021-01-01 14:43
Confirmed to work, thank you!

**Comment by arsenetar** [comment] 2021-08-19 02:32
Effectively this ends up being a duplicate of #484 or has been resolved in newer versions.

**Closed as completed by arsenetar** 2021-08-19 02:32 UTC
Labels: bug, Linux
