### ISSUE TITLE
error on catalina when scanning photographs

### ISSUE THREAD

**Issue by lawzeus** [arsenetar/dupeguru#722] opened 2020-10-07 10:08 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 / OSX 10.15 / Ubuntu 20.04]
 - Version [e.g. 4.0.4]

**Additional context**
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.15.7 (Build 19H2)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
a  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__KeyError: b'id:31673'

**Comment by glubsy** [comment] 2020-10-07 15:18
This has been reported many times already, and is supposedly fixed in version 4.0.4. Unfortunately there is no package for MacOS right now, so you'll have to build and install from this git repository to fix the problem.

**Comment by arsenetar** [comment] 2021-08-22 00:30
Duplicate of #439

**Closed as completed by arsenetar** 2021-08-22 00:30 UTC
Labels: bug
