### ISSUE TITLE
Application Name: dupeGuru Version: 4.1.1  Traceback (most recent call last):   File "qt\details_table.py", line 64, in headerData   File "core\gui\details_panel.py", line 42, in row_count AttributeError: 'DetailsPanel' object has no attribute '_table'

### ISSUE THREAD

**Issue by KONEBAK** [arsenetar/dupeguru#881] opened 2021-05-04 18:33 UTC
Application Name: dupeGuru
Version: 4.1.1

Traceback (most recent call last):
  File "qt\details_table.py", line 64, in headerData
  File "core\gui\details_panel.py", line 42, in row_count
AttributeError: 'DetailsPanel' object has no attribute '_table'

**Comment by glubsy** [comment] 2021-05-05 20:30
Most likely duplicate of #857.

**Closed as completed** 2021-08-28 09:30 UTC
Labels: bug
