### ISSUE TITLE
Trisquel 9.1 (an ubuntu deriv) throws a missing module error

### ISSUE THREAD

**Issue by mmmmna** [arsenetar/dupeguru#974] opened 2022-03-04 22:21 UTC
Used GDebi to install version `dupeGuru 4.1.1-0~ppa~focal1`. GDebi reported all dependencies were resolved, and reported no failure post install.

mmmmna@Opti9020Trisquel901:~$ /usr/bin/dupeguru 
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 89, in <module>
    sys.exit(main())
  File "/usr/bin/dupeguru", line 72, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 24, in <module>
    from . import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from . import (  # noqa
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from ._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2  # NOQA
ModuleNotFoundError: No module named 'core.pe._block'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_dupeguru_run.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 89, in <module>
    sys.exit(main())
  File "/usr/bin/dupeguru", line 72, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 24, in <module>
    from . import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from . import (  # noqa
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from ._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2  # NOQA
ModuleNotFoundError: No module named 'core.pe._block'
mmmmna@Opti9020Trisquel901:~$ 

Might I have grabbed the wrong release for my distro?

**Comment by arsenetar** [comment] 2022-03-09 13:52
This is essentially a duplicate of the issues #866 and related #484

**Closed as completed by arsenetar** 2022-03-09 13:52 UTC
