### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by herringb** [arsenetar/dupeguru#574] opened 2019-06-10 16:23 UTC
Application Name: dupeGuru
Version: 4.0.4 RC

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 101, in pulse
  File "core\app.py", line 323, in _job_error
  File "hscommon\jobprogress\performer.py", line 43, in _async_run
  File "core\app.py", line 780, in do
  File "core\scanner.py", line 137, in get_dupe_groups
  File "core\scanner.py", line 82, in _getmatches
  File "core\engine.py", line 269, in getmatches_by_contents
MemoryError

[Capture](https://user-images.githubusercontent.com/28162612/59209931-0ea90000-8b72-11e9-984d-586b4695d8d0.JPG)

**Comment by arsenetar** [comment] 2019-12-31 23:14
Duplicate of #507

**Closed as completed by arsenetar** 2019-12-31 23:14 UTC
Labels: bug
