### ISSUE TITLE
Photos app causes crash?

### ISSUE THREAD

**Issue by what2be** [arsenetar/dupeguru#435] opened 2017-08-18 04:28 UTC
For whatever reason, ver 4.03 will crash when trying to perform a scan using the "Pictures" category. I tried deleting the Photos Library.photoslibrary but still gave the same error. Works It great if I choose the "Standard" setting but "Pictures" gives this error:

==============
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.12.6 (Build 16G29)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Users/macbookpro/Pictures/Photos Library.photoslibrary/resources/proxies/derivatives/33/00/3394/UNADJUSTEDNONRAW_thumb_3394.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Users/macbookpro/Pictures/Photos Library.photoslibrary/resources/proxies/derivatives/33/00/3394/UNADJUSTEDNONRAW_thumb_3394.jpg'

**Comment by arsenetar** [comment] 2019-12-31 22:36
Looks to be a duplicate of #439 

I just built new initial binaries for OSX for 4.0.4 which most likely fixes this issue, over at: #566 (comment). If you would like to give one of those a try and let me know if that works that would be helpful.

**Closed** 2019-12-31 23:04 UTC
Labels: OSX, bug
