### ISSUE TITLE
Error opening 4.0.3, selecting files, and scanning

### ISSUE THREAD

**Issue by mattbouchard** [arsenetar/dupeguru#401] opened 2016-12-03 18:11 UTC
I get an error on opening:
![error-dupeguru-errorreport-2016-12-03](https://cloud.githubusercontent.com/assets/2067365/20861268/c803f52c-b948-11e6-9038-f4e0770ebdb3.png)

I can't copy and paste the text of that error (can't select it , click on it, anything). Then I add my folder:
![error-dupeguru-folderselection-2016-12-03](https://cloud.githubusercontent.com/assets/2067365/20861272/eb21d7b8-b948-11e6-96e2-8e07ecc23363.png)

![error-dupeguru-folderselection-select-2016-12-03](https://cloud.githubusercontent.com/assets/2067365/20861273/f4f19cb0-b948-11e6-801b-ece002eadf24.png)

Then, despite the list being empty, it tells me that folder is already in the list:

![error-dupeguru-folderselection-selecterror-2016-12-03](https://cloud.githubusercontent.com/assets/2067365/20861274/04cbaba8-b949-11e6-9853-e487af790cb8.png)

Then it stays on scanning indefinitely:

![error-dupeguru-scanning-2016-12-03](https://cloud.githubusercontent.com/assets/2067365/20861277/1807553c-b949-11e6-95e9-00701845d51b.png)

OS X Yosemite (10.10.5)

This is even on a clean install. I did a 
% sudo find / -xdev -name "*dupeguru*"
and deleted everything I found then did a fresh install. Error still occurs. Any advice?

**Comment by jasonology** [comment] 2017-10-10 04:01
I have the same problem but the error is different. Here’s my crash dump:
`Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.10.5 (Build 14F2511)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:35288'
`

**Comment by arsenetar** [comment] 2019-12-31 22:39
@jasonology Your issue is most likely a duplicate of the issue reported in #439

**Closed** 2021-08-19 02:27 UTC
