### ISSUE TITLE
Error while searching for duplicates.

### ISSUE THREAD

**Issue by bazza9** [arsenetar/dupeguru#764] opened 2021-01-15 22:44 UTC
**Describe the bug**
Tried to scan a folder for duplicate photos/videos Got the following error, which I've pasted below. Just to mention, my folder is on a QNAP NAS and I was running dupe guru from my Mac.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 / OSX 10.15 / Ubuntu 20.04 / Arch Linux]
 - Version [e.g. 4.1.0]

**Additional context**
Add any other context about the problem here. You may include the debug log although it is normally best to attach it as a file.

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.16 (Build 20C69)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 64, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 54, in get_cache
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 38, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 243, in open
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 227, in __init__
  File "build/dupeGuru.app/Contents/Resources/py/dbm/__init__.py", line 94, in open
_dbm.error: [Errno 79] Inappropriate file type or format

**Comment by arsenetar** [comment] 2021-08-19 02:17
Duplicate of #437, closing this one.

**Closed as completed by arsenetar** 2021-08-19 02:17 UTC
Labels: bug
