### ISSUE TITLE
Program crashed after loading and began scanning

### ISSUE THREAD

**Issue by rusty02139** [arsenetar/dupeguru#557] opened 2019-02-21 21:30 UTC
## Debug Log
```Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.14.2 (Build 18C54)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Users/jwoozle/Pictures/iPhoto Library.migratedphotolibrary/Thumbnails/2009/05/07/20090507-144441/855648EF-3FB4-4C8A-B0EC-F4631186B013/thumb_Warning_Small_1024.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Users/jwoozle/Pictures/iPhoto Library.migratedphotolibrary/Thumbnails/2009/05/07/20090507-144441/855648EF-3FB4-4C8A-B0EC-F4631186B013/thumb_Warning_Small_1024.jpg'
f reporting an error provide the debug log and/or the error message information.  If the debug log is short < 40 lines you can provide it here, otherwise attach the text file to this issue.
```

# Feature Requests
`Provide a detailed description of the feature.`

**Comment by arsenetar** [comment] 2019-12-31 22:10
Duplicate of #439. 

I just built new initial binaries for OSX for 4.0.4 which most likely fixes this issue, over at: https://github.com/arsenetar/dupeguru/issues/566#issuecomment-569992117.  If you would like to give one of those a try and let me know if that works that would be helpful.

**Closed** 2019-12-31 23:05 UTC
Labels: OSX, bug
