### ISSUE TITLE
DupeGuru error

### ISSUE THREAD

**Issue by C30303030** [arsenetar/dupeguru#532] opened 2018-10-29 04:42 UTC
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.13.6 (Build 17G65)

This happened when I selected Application Mode: Picture, ScanType: Contents.
thanks!

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 64, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 53, in get_cache
ImportError: No module named 'core.pe.cache_shelve'

**Comment by san-nas-san** [comment] 2018-11-20 16:57
I encountered the same error, I think it was caused by a large:
**cached_pictures.shelve.db**

At least after deleting the app including  

~/Library/Application Support/dupeGuru/cached_pictures.shelve.db

and reinstalling DupeGuru  it worked again, maybe there is a size limitation to the cache[..].db

Hope this infomay may help somreone else **:-)**

**Comment by arsenetar** [comment] 2022-03-19 23:15
4.0.3 is a rather old version, I am closing all issues related to it as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue

**Closed by arsenetar** 2022-03-19 23:15 UTC
Labels: bug
