### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cecilieaux** [arsenetar/dupeguru#309] opened 2015-05-24 23:04 UTC
```
Application Name: dupeGuru Music Edition
Version: 6.8.1

Traceback (most recent call last):
  File "/usr/share/dupeguru_me/qtlib/selectable_list.py", line 26, in data
    return self.model[index.row()]
  File "/usr/share/dupeguru_me/hscommon/gui/selectable_list.py", line 115, in __getitem__
    return self._items.__getitem__(key)
IndexError: list index out of range
```

**Comment by hsoft** [comment] 2015-05-24 23:14
Could you please provide a bit more context? What action did you perform just prior to this error?

**Comment by cecilieaux** [comment] 2015-05-25 00:27
Oh, I thought the message would suggest what it was. I was trying to
re-prioritize and after choosing shortest filenames I went and tried to
choose also a type. That crashed it.

On Sun, May 24, 2015 at 7:14 PM, Virgil Dupras <notifications@github.com>
wrote:

> Could you please provide a bit more context? What action did you perform
> just prior to this error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hsoft/dupeguru/issues/309#issuecomment-105078092>.
>



-- 

blogging at / blogueo en
¡Cecilieaux! musings of a contrarian <http://cecilieaux.blogspot.com/>
Let Mountains Hear - an electronic catacomb
<http://letmountainshear.blogspot.com/>
Desde Yanquilandia -- entre allá y acá
<http://desdeyanquilandia.blogspot.com/>

**Comment by hsoft** [comment] 2015-05-25 01:12
Thanks for the extra details. No, not all tracebacks give enough information to reproduce a problem. This one just tell me that at some point we were trying to fetch data for a table row and that this row didn't exist.

With these details, we have a better chances of having steps to reproduce the crash.

**Comment by cecilieaux** [comment] 2015-05-25 12:03
I should say also, it's a great little program. I have it on my laptop, too.

On Sun, May 24, 2015 at 9:12 PM, Virgil Dupras <notifications@github.com>
wrote:

> Thanks for the extra details. No, not all tracebacks give enough
> information to reproduce a problem. This one just tell me that at some
> point we were trying to fetch data for a table row and that this row didn't
> exist.
>
> With these details, we have a better chances of having steps to reproduce
> the crash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hsoft/dupeguru/issues/309#issuecomment-105083549>.
>



-- 

blogging at / blogueo en
¡Cecilieaux! musings of a contrarian <http://cecilieaux.blogspot.com/>
Let Mountains Hear - an electronic catacomb
<http://letmountainshear.blogspot.com/>
Desde Yanquilandia -- entre allá y acá
<http://desdeyanquilandia.blogspot.com/>

**Comment by hsoft** [comment] 2015-12-26 16:31
Probably related to #283

**Comment by arsenetar** [comment] 2022-03-19 23:48
This is a rather old version, I am closing all issues related to 4.0.3 and older as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue.

**Closed by arsenetar** 2022-03-19 23:48 UTC
Labels: bug
