### ISSUE TITLE
DupeGuru Photo Edition Freezes (24+ hours)

### ISSUE THREAD

**Issue by mugen2099** [arsenetar/dupeguru#371] opened 2016-06-23 12:31 UTC
I have 90K photos and videos to be scanned, but twice now, the tool freezes at 73% in the chunk matches process both times at 4456 of 4465. Not sure what's happening, but it's disappointing.

**Comment by hsoft** [comment] 2016-08-16 22:55
Without some more background information, this bug is going to be hard to reproduce, and thus to fix.

**Comment by arsenetar** [comment] 2022-03-19 23:45
Closing due to lack of details.

**Closed by arsenetar** 2022-03-19 23:45 UTC
Labels: bug, hold
