### ISSUE TITLE
Got key error while scanning a large folder

### ISSUE THREAD

**Issue by ayajurvedi** [arsenetar/dupeguru#723] opened 2020-10-07 14:27 UTC
Got the error report while scanning a large folder with, Application mode as "Picture" and Scan Type as "Contents". If it help this folder is on an external drive having NTFS.

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.15.7 (Build 19H2)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:37781'

**Comment by glubsy** [comment] 2020-10-07 15:19
This has been reported many times already, and is supposedly fixed in version 4.0.4. Unfortunately there is no package for MacOS right now, so you'll have to build and install from this git repository to fix the problem.

**Comment by MartinMeo** [comment] 2020-10-19 18:52
Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.15.7 (Build 19H2)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 129, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 47, in __delitem__
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 128, in __delitem__
KeyError: b'id:162976'

**Comment by MartinMeo** [comment] 2020-10-19 18:53
Do you know when the MacOS package for version 4.04 will be released?

**Comment by glubsy** [comment] 2020-10-19 19:32
> Do you know when the MacOS package for version 4.04 will be released?

Probably never, because building packages for MacOS is a total pain. But I have not looked into it very thoroughly. 

Feel free to build the application from this repository in the meantime.

**Comment by MartinMeo** [comment] 2020-10-20 06:07
Hi Faun,

I don’t know how to do that.
Do you have any instructions on how?

Cheers,
Martin

**Comment by glubsy** [comment] 2020-10-21 01:35
Probably something along the line of:
`git clone https://github.com/arsenetar/dupeguru.git && cd dupeguru`
`pip3 install virtualenv`
`python3 -m venv env && source ./env/bin/activate`
`pip3 install pyqt5`
`pip3 install -r requirements.txt`
`python3 build.py`
`make run`
Good luck. Using MacOS is always a total mess. 

Side note: I couldn't build a DMG package with the [dupeguru-cocoa repo](https://github.com/arsenetar/dupeguru-cocoa). I keep getting a `module __main__ has no attribute PyDupeGuru` exception while trying to run the build. 
I suspect the repo has actually never worked and that's why @arsenetar did not release a 4.0.4 DMG package.

**Comment by arsenetar** [comment] 2021-08-22 00:27
The mac versions have been updated, I would recommend trying the latest version.

**Comment by arsenetar** [comment] 2021-08-22 00:31
Duplicate of #439

**Closed as completed by arsenetar** 2021-08-22 00:31 UTC
Labels: bug
