### ISSUE TITLE
the PPA does not work with linux mint 20

### ISSUE THREAD

**Issue by blueray453** [arsenetar/dupeguru#712] opened 2020-09-14 15:17 UTC
**Describe the bug**
the PPA does not work with linux mint 20

**To Reproduce**
```
% sudo add-apt-repository ppa:dupeguru/ppa
Cannot add PPA: ''This PPA does not support focal''.
```

**Expected behavior**
I was expecting to use a PPA to install dupeguru in Linux Mint 20

**Desktop (please complete the following information):**
 - OS: Linux Mint 20

**Comment by glubsy** [comment] 2020-09-14 17:56
Apparently that PPA needs updating.

**Comment by s22merlin** [comment] 2020-09-15 12:56
same Problem in OS Mint 20
sudo add-apt-repository ppa:dupeguru/ppa
PPA kann nicht hinzugefügt werden: »'Dieses PPA unterstützt focal nicht'«.

**Comment by stellarpower** [comment] 2020-09-23 23:01
The build instructions in the readme for generating a package worked for me and the package has installed successfully. Could Focal be added to the PPA in launchpad easily enough?

**Comment by bernd-wechner** [comment] 2020-10-10 00:32
In the mean time @stellarpower, would you mind sharing the package to save us the need to build locally? Just curious.

**Comment by stellarpower** [comment] 2020-10-10 00:47
Sure, I was going to at the time but decided to shelve it and work on what I needed to at the time as wasn't sure where I could upload it easily. If you have any suggestions of suitable upload sites that would be helpful, if not I guess I could make a dummy repo. I'll have to get back to you as I can't get access to my system for a little longer :)

**Comment by stellarpower** [comment] 2020-10-28 18:13
I realise as I have a launchpad account I may be able to create a PPA, I'll look into that and see if that's easier.

**Comment by soredake** [comment] 2020-10-31 09:14
```
git clone --depth=1 https://github.com/arsenetar/dupeguru /tmp/dupeguru
cd /tmp/dupeguru || exit 1
bash -c "python3 -m venv --system-site-packages env && source env/bin/activate && pip install -r requirements.txt && python3 build.py --clean && python3 package.py"
cd build || exit 1
sudo apt install ./dupeguru*.deb
```

**Comment by arsenetar** [comment] 2021-08-19 02:26
Closing this as it is effectively a duplicate of https://github.com/arsenetar/dupeguru/issues/484

**Closed as completed by arsenetar** 2021-08-19 02:26 UTC
Labels: bug
