### ISSUE TITLE
Help: Dupeguru PE crashes after searching and displaying results

### ISSUE THREAD

**Issue by Ahjuya2** [arsenetar/dupeguru#600] opened 2019-10-09 13:19 UTC
I get the following code when the application crashes. I apologize but I am a regular user with no programming background but this app was very useful and the most accurate. If anyone can suggest another app that is fine but I tried so many with no success.
Thank you

Application Identifier: com.hardcoded-software.dupeguru-pe
Application Version: 2.10.0
Mac OS X Version: Version 10.14.5 (Build 18F132)

Traceback (most recent call last):
  File "build/dupeGuru PE.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru PE.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 95, in pulse
  File "build/dupeGuru PE.app/Contents/Resources/py/jobprogress/performer.py", line 59, in reraise_if_error
  File "build/dupeGuru PE.app/Contents/Resources/py/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru PE.app/Contents/Resources/py/core/app.py", line 724, in do
  File "build/dupeGuru PE.app/Contents/Resources/py/core/scanner.py", line 128, in get_dupe_groups
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/scanner.py", line 21, in _getmatches
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/matchblock.py", line 157, in getmatches
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/matchblock.py", line 58, in prepare_pictures
  File "build/dupeGuru PE.app/Contents/Resources/py/core_pe/cache.py", line 152, in purge_outdated
sqlite3.OperationalError: disk I/O error

**Comment by arsenetar** [comment] 2019-12-31 22:12
I would update to the latest version 4.0.3 at https://dupeguru.voltaicideas.net/ and see if you still have the issue.

**Comment by datcrack** [comment] 2020-01-28 20:34
Application Version: 4.0.3
Mac OS X Version: Version 10.15 (Build 19A583)
Still has the issue for Catalina.

**Comment by fuzzy76** [comment] 2020-03-26 12:32
Is this a duplicate of #439 ?

**Closed as completed** 2021-08-19 02:27 UTC
Labels: bug, macOS
