### ISSUE TITLE
phot mode match errors out//large volume

### ISSUE THREAD

**Issue by canuk99** [arsenetar/dupeguru#850] opened 2021-03-01 13:41 UTC
**Describe the bug**

**To Reproduce**

checked a large nas mounted(cifs) volume for dup pictures.

got up in the morning to an error:

Application Identifier: com.hardcoded-software.dupeguru
Application Version: 4.0.3
Mac OS X Version: Version 10.15.7 (Build 19H524)

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 111, in __getitem__
KeyError: 'path:/Volumes/Multimedia/photos/2004/02/IMG_2574_20040227_130002(1).JPG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/cocoa/inter.py", line 259, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/gui/progress_window.py", line 101, in pulse
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 323, in _job_error
  File "build/dupeGuru.app/Contents/Resources/py/hscommon/jobprogress/performer.py", line 43, in _async_run
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 780, in do
  File "build/dupeGuru.app/Contents/Resources/py/core/scanner.py", line 137, in get_dupe_groups
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/scanner.py", line 31, in _getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 167, in getmatches
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/matchblock.py", line 65, in prepare_pictures
  File "build/dupeGuru.app/Contents/Resources/py/core/pe/cache_shelve.py", line 121, in purge_outdated
  File "build/dupeGuru.app/Contents/Resources/py/shelve.py", line 113, in __getitem__
KeyError: b'path:/Volumes/Multimedia/photos/2004/02/IMG_2574_20040227_130002(1).JPG'
![version_apple](https://user-images.githubusercontent.com/65252146/109504748-e231c780-7a69-11eb-99ff-d1e06a3446d5.png)

**Comment by arsenetar** [comment] 2021-08-19 02:15
I recommend trying the latest version there has been some work to correct this issue.

**Comment by arsenetar** [comment] 2021-08-22 00:34
Duplicate of #439.

**Closed as completed by arsenetar** 2021-08-22 00:34 UTC
Labels: bug
