### ISSUE TITLE
why did you use Wacatac trojan?

### ISSUE THREAD

**Issue by JuanJ67m** [arsenetar/dupeguru#771] opened 2021-01-24 23:37 UTC
wtf guys

![image](https://user-images.githubusercontent.com/4990279/105647361-1a465900-5e73-11eb-9d17-dd4233f69a2b.png)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.B!ml&threatid=2147735505

I installed from here:

https://chocolatey.org/packages?q=dupeGuru

**Comment by arsenetar** [comment] 2021-01-25 04:48
Have you tried the official packages at https://github.com/arsenetar/dupeguru/releases/tag/4.1.0? We do not have an official chocolatey package so I can not say if that package matches the official files.  I have not seen this issue with the official packages on my computer.

**Comment by arsenetar** [comment] 2021-01-25 05:14
It appears chocolatey "should" be using the official files from what I can see in the package script.

**Comment by arsenetar** [comment] 2021-03-22 05:36
Closing as can not reproduce and not seeing this in the scans of our provided files.

**Closed as completed by arsenetar** 2021-03-22 05:36 UTC
Labels: bug

**Comment by Sei-lus** [comment] 2021-03-24 03:28
Reopening.
![image](https://user-images.githubusercontent.com/57790936/112250228-ec9e4600-8c50-11eb-93bb-5cbe5839a55b.png)

Installed from Github or here https://dupeguru.voltaicideas.net/

Edit: I'm not claiming you are bundling malware. I'm claiming it was identified as malware by Windows Defender.
I don't know if you will be able to reproduce but something I have done that may be abnormal to other users.

Installed.
Ran .exe
Looked for duplicates by filename in X directory.
Cleaned.
Looked for duplicates by content in X directory.
Cleaned.
Looked for image duplicates by content in X directory. Took a while and fell asleep.
Looked at the duplicates this morning but they are too many because they are very similar so I saved the results and left the program open.
About mid day I received a warning from Windows Defender. I ignored it until now. Program still open with the results from the image content duplicate search.

![image](https://user-images.githubusercontent.com/57790936/112250915-2f145280-8c52-11eb-8d46-964e6d47289a.png)

Will wait for reply to allow or delete.
