### ISSUE TITLE
Dupe Guru crashes when scanning for duplicates

### ISSUE THREAD

**Issue by jonas2295** [arsenetar/dupeguru#584] opened 2019-07-27 10:55 UTC
# Bug / issue Report
Application Name: dupeGuru
Version: 4.0.4 RC

## Description
All I am doing is set the program to scan my folder with around 80k files and then after about an hour this traceback error screen shows up.

## Debug Log
```
If reporting an error provide the debug log and/or the error message information.  If the debug log is short < 40 lines you can provide it here, otherwise attach the text file to this issue.
```

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 101, in pulse
  File "core\app.py", line 323, in _job_error
  File "hscommon\jobprogress\performer.py", line 43, in _async_run
  File "core\app.py", line 780, in do
  File "core\scanner.py", line 137, in get_dupe_groups
  File "core\pe\scanner.py", line 31, in _getmatches
  File "core\pe\matchblock.py", line 167, in getmatches
  File "core\pe\matchblock.py", line 83, in prepare_pictures
  File "core\pe\photo.py", line 105, in get_blocks
  File "qt\pe\photo.py", line 36, in _plat_get_blocks
TypeError: '<=' not supported between instances of 'int' and 'str'

**Comment by arsenetar** [comment] 2019-12-31 23:12
Duplicate of #551

**Closed as completed by arsenetar** 2019-12-31 23:12 UTC
Labels: bug
