### ISSUE TITLE
“dupeGuru.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by eta-orionis** [arsenetar/dupeguru#956] opened 2021-12-08 23:15 UTC
**Describe the bug**
Catalina 10.15.7 does not open the app, saying "“dupeGuru.app” can’t be opened because Apple cannot check it for malicious software."

(I know I can override system security to allow the app to run, but I'd rather prefer not doing it; also I don't remember ever getting this error from trying to run dupeGuru)

**To Reproduce**
1. Download latest release dmg
2. Double-click to mount the DMG
3. Move dupeGuru.app to /Applications
4. Try running dupeGuru.app

**Expected behavior**
App opens and is ready to work

**Screenshots**
![image](https://user-images.githubusercontent.com/3466670/145306154-04609497-cb55-4b60-8483-7c110259b05d.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X Catalina 
 - Version 10.15.7, all security updates

**Comment by glubsy** [comment] 2021-12-09 01:10
Seems to be related to #945.

**Comment by arsenetar** [comment] 2021-12-09 03:40
This is interesting, a bit different of an error than I have seen before.  If it is related to #945 then the only way to solve it is paying for the developer subscription.

**Comment by arsenetar** [comment] 2022-01-25 00:07
Looking at this a bit more going to mark as a duplicate of #945.

**Closed as completed by arsenetar** 2022-01-25 00:07 UTC
Labels: bug

**Comment by porteusconf** [comment] 2022-01-27 15:19
Possible-work-around:

 Open Terminal and paste in following command(s):
```
 /Applications/dupeguru.app/Contents/MacOS/dupeguru 
```
Posted details at closed #945 [https://github.com/arsenetar/dupeguru/issues/945#issuecomment-1023317428](https://github.com/arsenetar/dupeguru/issues/945#issuecomment-1023317428)
